# Generated by Django 3.2.7 on 2021-10-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuiseiRadio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='suisei_albums',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='suisei_artists',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='suisei_ratings',
        ),
        migrations.AlterModelTable(
            name='review',
            table='suisei_reviews',
        ),
        migrations.AlterModelTable(
            name='song',
            table='suisei_songs',
        ),
    ]
