# Generated by Django 3.2.7 on 2021-10-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuiseiRadio', '0002_auto_20211026_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=60)),
                ('song_cover', models.ImageField(upload_to='song_covers', verbose_name='image')),
                ('song_file', models.FileField(upload_to='')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SuiseiRadio.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuiseiRadio.artist')),
            ],
        ),
    ]
