# Generated by Django 3.2.7 on 2021-10-27 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SuiseiRadio', '0003_alter_like_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('album', 'author')},
        ),
    ]
